import type { LucideIcon } from "lucide-react";
import {
  Bean,
  Beef,
  CakeSlice,
  CircleDashed,
  CupSoda,
  Cylinder,
  Diamond,
  Droplets,
  Drumstick,
  Egg,
  EggFried,
  Ham,
  IceCreamCone,
  LeafyGreen,
  Pin,
  Salad,
  Sandwich,
  Shell,
  Soup,
  Sprout,
  SquarePlus,
  SquareUser,
  ToggleLeft,
  Torus,
  Tractor,
  Triangle,
  Utensils,
  UtensilsCrossed,
  Waves,
} from "lucide-react";

export const CHIPOTLE_CATEGORY_ICONS: Record<string, LucideIcon> = {
  sandwich: Sandwich,
  sandwiches: Sandwich,
  "sandwich toppings": LeafyGreen,
  toppings: LeafyGreen,
  chicken: Drumstick,
  proteins: Drumstick,
  rice: Sprout,
  beans: Bean,
  "included ingredient": Pin,
  "included ingredients": Pin,
  base: Pin,
  "breakfast protein": Drumstick,
  condiments: Utensils,
  "salad condiments": Utensils,
  salads: Salad,
  "salad toppings": Salad,
  drinks: CupSoda,
  "fountain drinks": CupSoda,
  "tractor beverages": Tractor,
  "kids drinks": SquareUser,
  breakfast: EggFried,
  "breakfast side": Torus,
  "breakfast sides": Torus,
  kids: SquareUser,
  sides: SquarePlus,
  side: CircleDashed,
  desserts: CakeSlice,
  wraps: Shell,
  "wrap toppings": Waves,
  burgers: Beef,
  entrees: Utensils,
  "bowls & plates": Soup,
  buns: CircleDashed,
  "breakfast buns": CircleDashed,
  cheeses: Diamond,
  eggs: Egg,
  "soup toppings": Soup,
  "parfait toppings": IceCreamCone,
  "treat toppings": IceCreamCone,
  dressings: Droplets,
  "dipping sauces": ToggleLeft,
  "chips & dips": Triangle,
  "single sides": Cylinder,
  "protein meals": UtensilsCrossed,
  "protein cups": Ham,
  treats: IceCreamCone,
};
